/*
-- Query: SELECT * FROM graduation.barcodeprinter
LIMIT 0, 50000

-- Date: 2022-10-27 16:31
*/
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (1,'codeprinter-e9935351c20d','条码打印机','吊牌','2022-10-21','41号工作站','金龙鱼生产线','PET标签','2880*3100','云禹辰','财务部','永康市瑞扬工贸有限公司','水果批发');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (2,'codeprinter-b8b2d777f302','条码打印机','PET标签','2022-10-21','17号工作站','金枪鱼生产线','PET标签','720*1240','薛淳美','安全监察部','深圳市瑞鸿鑫贸易有限公司','水果批发');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (3,'codeprinter-6b80dee79670','条码打印机','吊牌','2022-10-21','43号工作站','马哈鱼生产线','热敏纸打印不干胶标签','2880*3100','岑昊轩','财务部','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','大物体');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (6,'codeprinter-fabdf0d9c5c1','条码打印机','不干胶标签','2022-10-21','2号工作站','金龙鱼生产线','热敏纸打印不干胶标签','0*620','沈国栋','行政办公室','永康市瑞扬工贸有限公司','体重');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (7,'codeprinter-13a50da50a6d','条码打印机','PET标签','2022-10-21','16号工作站','鱿鱼丝生产线','PET标签','720*1240','奚萌萌','安全监察部','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','家用小称');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (9,'codeprinter-c3b992ff5cc9','条码打印机','水洗布','2022-10-21','10号工作站','金龙鱼生产线','吊牌','720*1240','唐建林','行政办公室','东莞市诚有成电子有限公司','体重');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (10,'codeprinter-a8b824830571','条码打印机','PET标签','2022-10-21','47号工作站','鱿鱼丝生产线','吊牌','2880*3100','花汝鑫','行政办公室','介花潮公司','大物体');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (11,'codeprinter-a7ac49d9a10c','条码打印机','不干胶标签','2022-10-21','29号工作站','鱿鱼丝生产线','热敏纸打印不干胶标签','1440*1860','谢佳玉','生产技术部','深圳市瑞鸿鑫贸易有限公司','家用小称');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (12,'codeprinter-6837f7eea926','条码打印机','PET标签','2022-10-21','10号工作站','鱿鱼丝生产线','水洗布','720*1240','马昕蕊','生产技术部','永康市瑞扬工贸有限公司','大物体');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (13,'codeprinter-ccaa382d947d','条码打印机','水洗布','2022-10-21','56号工作站','金龙鱼生产线','PET标签','3600*3720','窦禹辰','人力资源部','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','家用小称');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (15,'codeprinter-3abf38f3172b','条码打印机','POSTEK标签','2022-10-21','8号工作站','鱿鱼丝生产线','热敏纸打印不干胶标签','0*620','喻嘉乐','财务部','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','水产');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (16,'codeprinter-7cb9554164c3','条码打印机','PET标签','2022-10-21','40号工作站','鱿鱼丝生产线','水洗布','2880*3100','薛泽远','计划营销部','介花潮公司','家用小称');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (17,'codeprinter-f7dc49c898e4','条码打印机','水洗布','2022-10-21','31号工作站','金枪鱼生产线','PET标签','2160*2480','常禹辰','安全监察部','深圳市博途电子科技有限公司','家用小称');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (18,'codeprinter-49f900ec2dfb','条码打印机','PET标签','2022-10-21','26号工作站','金龙鱼生产线','水洗布','1440*1860','萧晓庆','计划营销部','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','海鲜');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (19,'codeprinter-9833007c81a7','条码打印机','PET标签','2022-10-21','39号工作站','马哈鱼生产线','吊牌','2160*2480','水淑君','生产技术部','深圳市博途电子科技有限公司','大物体');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (20,'codeprinter-5c87962d0c22','条码打印机','POSTEK标签','2022-10-21','40号工作站','金龙鱼生产线','热敏纸打印不干胶标签','2880*3100','蒋晶滢','安全监察部','广州依芭衫工艺品商行','海鲜');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (22,'codeprinter-147dcf7d157a','条码打印机','PET标签','2022-10-21','17号工作站','金枪鱼生产线','热敏纸打印不干胶标签','720*1240','平一鸣','计划营销部','广州依芭衫工艺品商行','大物体');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (23,'electronicscale-8a4463319bb9','台秤','条码打印机','2022-10-24','21号位','2022-10-24 23:26:26','条形码','1920*1080','深圳市瑞鸿鑫贸易有限公司','0~21','21','电子秤');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (24,'electronicscale-8a4463319bb9','台秤','条码打印机','2022-10-07','21号位','2022-10-24 23:26:26','条形码','1920*1080','深圳市瑞鸿鑫贸易有限公司','0~21','21','电子秤');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (25,'electronicscale-8a4463319bb9','条码打印机','条码打印机','2022-10-07','21号位','2022-10-24 23:26:26','条形码','1920*1080','深圳市瑞鸿鑫贸易有限公司','0~21','21','电子秤');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (26,'electronicscale-8a4463319bb9','条码打印机','条码打印机','2022-09-30','21号位','2022-10-24 23:26:26','条形码','1920*1080','深圳市瑞鸿鑫贸易有限公司','0~21','21','电子秤');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (27,'electronicscale-8a4463319bb9','台秤','条码打印机','2022-10-08','21号位','66666666666','条形码','1920*1080','深圳市瑞鸿鑫贸易有限公司','0~21','21','电子秤');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (28,'electronicscale-8a4463319bb9','台秤','条码打印机','2022-10-08 23:27:50','21号位','66666666666','条形码','1920*1080','深圳市瑞鸿鑫贸易有限公司','0~21','21','电子秤');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`DeviceType`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`PrintMode`,`ResolutionRatio`,`PrincipalOfAssets`,`DepartmentOfOwnership`,`manufacturing`,`USEfor`) VALUES (29,'42452','电子秤','条码打印机','2022-10-24 23:46:34','452452','45245','条形码','1920*1080','2452452','2452','45245','2452452');
