/*
-- Query: SELECT * FROM graduation.electronicscale
LIMIT 0, 50000

-- Date: 2022-10-27 16:32
*/
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (1,'electronicscale-45353453','电子秤','2022-10-19','鱿鱼丝生产线','1号位','案秤','0~10',5,'\'凯丰\'','北京启阳科技有限公司','\'市场采购\'','\'物产\'','\'MYY5155-11212\'','\'球球\'');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (3,'electronicscale-8a4463319bb9','电子秤','2022-10-21','马哈鱼生产线','21号位','台秤','0~21',21,'电子秤','深圳市瑞鸿鑫贸易有限公司','行政办公室','水果批发','ElectronicScale-8a4463319bb9','酆晨涛');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (4,'electronicscale-414bdf6e6fbc','电子秤','2022-10-21','鱿鱼丝生产线','55号位','杆秤','0~55',55,'弹簧秤','广州依芭衫工艺品商行','人力资源部','大物体','ElectronicScale-414bdf6e6fbc','毕建林');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (5,'electronicscale-fe6f748086ba','电子秤','2022-10-21','金龙鱼生产线','13号位','电子秤','0~13',13,'弹簧秤','永康市瑞扬工贸有限公司','生产技术部','水果批发','ElectronicScale-fe6f748086ba','平淼');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (6,'electronicscale-ac66bd3db2d6','电子秤','2022-10-21','金枪鱼生产线','19号位','案秤','0~19',19,'电子磅秤','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','人力资源部','大物体','ElectronicScale-ac66bd3db2d6','郎欣汝');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (7,'electronicscale-b85d22bb1834','电子秤','2022-10-21','马哈鱼生产线','53号位','电子秤','0~53',53,'杆秤','东莞市诚有成电子有限公司','技术部','机械制造','ElectronicScale-b85d22bb1834','华佳怡');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (8,'electronicscale-5b7039a41c42','电子秤','2022-10-21','金枪鱼生产线','31号位','电子磅秤','0~31',31,'案秤','永康市瑞扬工贸有限公司','财务部','机械制造','ElectronicScale-5b7039a41c42','皮冰枫');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (9,'electronicscale-4b90859c9fa4','电子秤','2022-10-21','鱿鱼丝生产线','34号位','托盘天平','0~34',34,'电子磅秤','深圳市博途电子科技有限公司','行政办公室','家用小称','ElectronicScale-4b90859c9fa4','酆润莎');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (10,'electronicscale-666a1bc9a228','电子秤','2022-10-21','马哈鱼生产线','43号位','台秤','0~43',43,'案秤','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','计划营销部','大物体','ElectronicScale-666a1bc9a228','水昊轩');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (11,'electronicscale-bd45be08e759','电子秤','2022-10-21','鱿鱼丝生产线','59号位','台秤','0~59',59,'台秤','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','生产技术部','体重','ElectronicScale-bd45be08e759','元淼');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (12,'electronicscale-d6e7b6b324c7','电子秤','2022-10-21','马哈鱼生产线','32号位','杆秤','0~32',32,'装载机电子秤','介花潮公司','计划营销部','大物体','ElectronicScale-d6e7b6b324c7','黄益冉');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (13,'electronicscale-4b3370b17810','电子秤','2022-10-21','金枪鱼生产线','61号位','杆秤','0~61',61,'台秤','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','行政办公室','海鲜','ElectronicScale-4b3370b17810','余明远');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (14,'electronicscale-c253d3df7c5d','电子秤','2022-10-21','鱿鱼丝生产线','25号位','托盘天平','0~25',25,'电子秤','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','计划营销部','机械制造','ElectronicScale-c253d3df7c5d','罗语晨');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (15,'electronicscale-eb426dfac92a','电子秤','2022-10-21','马哈鱼生产线','34号位','弹簧秤','0~34',34,'托盘天平','深圳市瑞鸿鑫贸易有限公司','技术部','水果批发','ElectronicScale-eb426dfac92a','李欣汝');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (16,'electronicscale-b09247bcfb2c','电子秤','2022-10-21','鱿鱼丝生产线','46号位','电子磅秤','0~46',46,'装载机电子秤','东莞市诚有成电子有限公司','计划营销部','大物体','ElectronicScale-b09247bcfb2c','袁涵涵');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (17,'electronicscale-a31aab6cc8f8','电子秤','2022-10-21','鱿鱼丝生产线','43号位','案秤','0~43',43,'台秤','深圳市瑞鸿鑫贸易有限公司','技术部','海鲜','ElectronicScale-a31aab6cc8f8','朱亦菲');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (18,'electronicscale-ea02fde51dce','电子秤','2022-10-21','金枪鱼生产线','16号位','电子秤','0~16',16,'弹簧秤','东莞市诚有成电子有限公司','财务部','海鲜','ElectronicScale-ea02fde51dce','常佳惠');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (19,'electronicscale-2ba75f9720a2','电子秤','2022-10-21','鱿鱼丝生产线','48号位','电子磅秤','0~48',48,'电子秤','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','技术部','水果批发','ElectronicScale-2ba75f9720a2','赵嘉乐');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (20,'electronicscale-b68e3d81453f','电子秤','2022-10-21','金龙鱼生产线','49号位','台秤','0~49',49,'弹簧秤','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','财务部','水果批发','ElectronicScale-b68e3d81453f','吕禹辰');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (21,'electronicscale-a176cacdbc47','电子秤','2022-10-21','鱿鱼丝生产线','11号位','杆秤','0~11',11,'装载机电子秤','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','行政办公室','水果批发','ElectronicScale-a176cacdbc47','赵淳美');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (22,'electronicscale-c57d06633daa','电子秤','2022-10-21','金龙鱼生产线','43号位','装载机电子秤','0~43',43,'杆秤','介花潮公司','财务部','家用小称','ElectronicScale-c57d06633daa','水萌');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (23,'electronicscale-e63145dd422b','电子秤','2022-10-21','马哈鱼生产线','46号位','装载机电子秤','0~46',46,'电子秤','东莞市诚有成电子有限公司','技术部','体重','ElectronicScale-e63145dd422b','平添池');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (24,'electronicscale-34e265c350a1','电子秤','2022-10-21','马哈鱼生产线','50号位','托盘天平','0~50',50,'案秤','深圳市博途电子科技有限公司','财务部','家用小称','ElectronicScale-34e265c350a1','昌贺祥');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (25,'electronicscale-e1d83e6d1d5c','电子秤','2022-10-21','马哈鱼生产线','16号位','电子秤','0~16',16,'案秤','深圳市瑞鸿鑫贸易有限公司','技术部','体重','ElectronicScale-e1d83e6d1d5c','穆文杰');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (26,'electronicscale-dd4f7e552177','电子秤','2022-10-21','鱿鱼丝生产线','46号位','弹簧秤','0~46',46,'电子磅秤','东莞市诚有成电子有限公司','计划营销部','家用小称','ElectronicScale-dd4f7e552177','鲍运昊');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (27,'electronicscale-e8ffa0053075','电子秤','2022-10-21','金龙鱼生产线','25号位','托盘天平','0~25',25,'装载机电子秤','东莞市诚有成电子有限公司','财务部','海鲜','ElectronicScale-e8ffa0053075','葛浩晨');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (28,'electronicscale-00eac0e0cb40','电子秤','2022-10-21','金龙鱼生产线','50号位','托盘天平','0~50',50,'案秤','深圳市博途电子科技有限公司','计划营销部','大物体','ElectronicScale-00eac0e0cb40','苗嘉怡');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (29,'electronicscale-06bd5169770b','电子秤','2022-10-21','金枪鱼生产线','16号位','杆秤','0~16',16,'台秤','深圳市瑞鸿鑫贸易有限公司','人力资源部','体重','ElectronicScale-06bd5169770b','平嘉乐');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (30,'electronicscale-5a7533d8ba33','电子秤','2022-10-21','金枪鱼生产线','60号位','电子秤','0~60',60,'装载机电子秤','深圳市博途电子科技有限公司','财务部','大物体','ElectronicScale-5a7533d8ba33','汤佳欣');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (31,'electronicscale-c0ec6810d71d','电子秤','2022-10-21','金枪鱼生产线','57号位','杆秤','0~57',57,'台秤','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','安全监察部','大物体','ElectronicScale-c0ec6810d71d','傅佳昊');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (32,'electronicscale-489c33ffb532','电子秤','2022-10-21','金枪鱼生产线','60号位','电子磅秤','0~60',60,'杆秤','广州依芭衫工艺品商行','人力资源部','水果批发','ElectronicScale-489c33ffb532','傅淼');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (33,'electronicscale-f4b76155a53e','电子秤','2022-10-21','鱿鱼丝生产线','20号位','装载机电子秤','0~20',20,'弹簧秤','广州依芭衫工艺品商行','生产技术部','水果批发','ElectronicScale-f4b76155a53e','杨明远');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (34,'electronicscale-42ad533cf329','电子秤','2022-10-21','金龙鱼生产线','6号位','电子秤','0~6',6,'案秤','深圳市贝约瀚有限公司','生产技术部','家用小称','ElectronicScale-42ad533cf329','史亦菲');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (35,'electronicscale-7a2cc7db5a9a','电子秤','2022-10-21','金龙鱼生产线','43号位','杆秤','0~43',43,'电子秤','深圳市博途电子科技有限公司','行政办公室','水果批发','ElectronicScale-7a2cc7db5a9a','殷欣源');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (36,'electronicscale-8a4463319bb9','电子秤','2022-10-24','马哈鱼生产线','21号位','2022-10-24T13:25:24.000Z','0~21',21,'电子秤','深圳市瑞鸿鑫贸易有限公司','行政办公室','水果批发','ElectronicScale-8a4463319bb9','酆晨涛');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (37,'电子秤','台秤','2022-10-24','马哈鱼生产线','21号位','2022-10-24T13:36:43.000Z','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (38,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','2022-10-24T13:38:08.000Z','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (39,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','2022-10-03T16:00:00.000Z','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (41,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (42,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (43,'electronicscale-8a4463319bb9','台秤','2022-10-05','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (44,'electronicscale-8a4463319bb9','台秤','2022-10-15','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (45,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (46,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (47,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (48,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (49,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (50,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (51,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
INSERT INTO `` (`id`,`BarCodeEquipment`,`specificationOfEquipment`,`purchasingPeriod`,`workStation`,`SubordinateStation`,`ScaleName`,`WeighingScale`,`weight`,`supplier`,`manufacturer`,`DepartmentOfOwnership`,`USEFor`,`manufacturing`,`PrincipalOfAssets`) VALUES (52,'electronicscale-8a4463319bb9','台秤','2022-10-24','马哈鱼生产线','21号位','电子秤','0~21',21,'深圳市瑞鸿鑫贸易有限公司','电子秤','酆晨涛','水果批发','行政办公室','ElectronicScale-8a4463319bb9');
