/*
-- Query: SELECT * FROM graduation.infraredcountergun
LIMIT 0, 50000

-- Date: 2022-10-27 16:37
*/
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (1,'yyyy-1515','红外对射枪','2019-01-16 06:06:16','红外','尤旭旭工作站','1号位',5,'12615454','外包装','红外厂商','球球','技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (2,'infraredcountergun-7dae2292de23','红外对射枪','2022-10-21 17:09:52','POSTEK标签','金龙鱼生产线','37号位',37,'infraredcounter-7dae2292de23','水产','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','冯淳美','行政办公室');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (4,'infraredcountergun-e38a2b13c774','红外对射枪','2022-10-21 17:10:01','不干胶标签','金龙鱼生产线','63号位',63,'infraredcounter-e38a2b13c774','大物体','介花潮公司','水昊轩','技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (5,'infraredcountergun-c4abdc148eb2','红外对射枪','2022-10-21 17:10:01','不干胶标签','马哈鱼生产线','31号位',31,'infraredcounter-c4abdc148eb2','体重','深圳市贝约瀚有限公司','毕淳美','财务部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (7,'infraredcountergun-dcee6c969a3a','红外对射枪','2022-10-21 17:10:04','水洗布','马哈鱼生产线','10号位',10,'infraredcounter-dcee6c969a3a','水产','东莞市诚有成电子有限公司','平浩晨','生产技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (8,'infraredcountergun-5a900be584f7','红外对射枪','2022-10-21 17:46:38','POSTEK标签','金龙鱼生产线','5号位',5,'infraredcounter-5a900be584f7','海鲜','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','于欣汝','计划营销部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (9,'infraredcountergun-079fecced8fd','红外对射枪','2022-10-21 17:46:58','POSTEK标签','金枪鱼生产线','28号位',28,'infraredcounter-079fecced8fd','水果批发','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','郑萌萌','技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (10,'infraredcountergun-d2dfadc98545','红外对射枪','2022-10-21 17:46:59','不干胶标签','金龙鱼生产线','32号位',32,'infraredcounter-d2dfadc98545','水果批发','深圳市贝约瀚有限公司','苗淳美','计划营销部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (11,'infraredcountergun-e94173daa99d','红外对射枪','2022-10-21 17:47:00','吊牌','鱿鱼丝生产线','51号位',51,'infraredcounter-e94173daa99d','水产','深圳市瑞鸿鑫贸易有限公司','褚佳毅','计划营销部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (12,'infraredcountergun-f25482ee277d','红外对射枪','2022-10-21 17:47:00','水洗布','金枪鱼生产线','44号位',44,'infraredcounter-f25482ee277d','水产','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','俞佳欣','安全监察部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (13,'infraredcountergun-2a9e693f92cc','红外对射枪','2022-10-21 17:47:01','PET标签','马哈鱼生产线','1号位',1,'infraredcounter-2a9e693f92cc','家用小称','东莞市诚有成电子有限公司','廉益冉','财务部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (14,'infraredcountergun-0967654395d4','红外对射枪','2022-10-21 17:47:04','PET标签','马哈鱼生产线','50号位',50,'infraredcounter-0967654395d4','水果批发','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','秦欣怡','行政办公室');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (15,'infraredcountergun-609cca2c05f6','红外对射枪','2022-10-21 17:47:07','水洗布','金枪鱼生产线','26号位',26,'infraredcounter-609cca2c05f6','水果批发','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','冯慧嘉','计划营销部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (16,'infraredcountergun-ff3ff5ac04f4','红外对射枪','2022-10-21 17:47:08','不干胶标签','金枪鱼生产线','52号位',52,'infraredcounter-ff3ff5ac04f4','水产','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','施欣怡','行政办公室');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (17,'infraredcountergun-96ce10d8a74a','红外对射枪','2022-10-21 17:47:08','吊牌','鱿鱼丝生产线','2号位',2,'infraredcounter-96ce10d8a74a','机械制造','深圳市博途电子科技有限公司','魏一鸣','技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (18,'infraredcountergun-0dc9a61a2e02','红外对射枪','2022-10-21 17:47:09','水洗布','金龙鱼生产线','40号位',40,'infraredcounter-0dc9a61a2e02','水产','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','朱伟洋','人力资源部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (19,'infraredcountergun-f36434f135b0','红外对射枪','2022-10-21 17:47:09','不干胶标签','马哈鱼生产线','32号位',32,'infraredcounter-f36434f135b0','海鲜','东莞市诚有成电子有限公司','邹汝鑫','安全监察部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (20,'infraredcountergun-7cb786cc224f','红外对射枪','2022-10-21 17:47:10','PET标签','金龙鱼生产线','41号位',41,'infraredcounter-7cb786cc224f','大物体','广州依芭衫工艺品商行','郎淑华','计划营销部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (21,'infraredcountergun-901bdee6bac9','红外对射枪','2022-10-21 17:47:10','不干胶标签','金枪鱼生产线','26号位',26,'infraredcounter-901bdee6bac9','体重','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','钱瑞堂','财务部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (22,'infraredcountergun-80a52703cb5a','红外对射枪','2022-10-21 17:47:53','PET标签','金龙鱼生产线','13号位',13,'infraredcounter-80a52703cb5a','水产','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','史嘉怡','生产技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (23,'infraredcountergun-1f4b012b7331','红外对射枪','2022-10-21 17:47:54','吊牌','金龙鱼生产线','33号位',33,'infraredcounter-1f4b012b7331','家用小称','深圳市瑞鸿鑫贸易有限公司','穆泽远','技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (24,'infraredcountergun-8ebb3d4d5f6d','红外对射枪','2022-10-21 17:47:55','PET标签','金龙鱼生产线','38号位',38,'infraredcounter-8ebb3d4d5f6d','机械制造','介花潮公司','卞杨','行政办公室');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (25,'infraredcountergun-db8164aab100','红外对射枪','2022-10-21 17:47:56','吊牌','马哈鱼生产线','4号位',4,'infraredcounter-db8164aab100','机械制造','东莞市诚有成电子有限公司','潘一鸣','技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (26,'infraredcountergun-5ba6dd0f00a7','红外对射枪','2022-10-21 17:47:56','POSTEK标签','马哈鱼生产线','24号位',24,'infraredcounter-5ba6dd0f00a7','水产','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','苏雄霖','生产技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (27,'infraredcountergun-bab4954b4d8a','红外对射枪','2022-10-21 17:48:04','PET标签','鱿鱼丝生产线','54号位',54,'infraredcounter-bab4954b4d8a','海鲜','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','韩亦菲','行政办公室');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (28,'infraredcountergun-81a3997fa08c','红外对射枪','2022-10-21 17:48:04','水洗布','金龙鱼生产线','33号位',33,'infraredcounter-81a3997fa08c','家用小称','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','潘冰枫','技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (29,'infraredcountergun-154d3b1c997e','红外对射枪','2022-10-21 17:48:05','水洗布','金龙鱼生产线','45号位',45,'infraredcounter-154d3b1c997e','水产','介花潮公司','时雅涵','安全监察部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (30,'infraredcountergun-4856b8b8139a','红外对射枪','2022-10-21 17:48:05','水洗布','马哈鱼生产线','2号位',2,'infraredcounter-4856b8b8139a','大物体','深圳市瑞鸿鑫贸易有限公司','蒋亦菲','安全监察部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (31,'infraredcountergun-66643c671fff','红外对射枪','2022-10-21 17:48:06','水洗布','金龙鱼生产线','45号位',45,'infraredcounter-66643c671fff','家用小称','深圳市博途电子科技有限公司','皮泽远','人力资源部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (32,'infraredcountergun-fac39e894c07','红外对射枪','2022-10-24 23:44:06','水洗布','金枪鱼生产线','49号位',49,'infraredcounter-fac39e894c07','水果批发','东莞市诚有成电子有限公司','尤晨璐','技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (33,'infraredcountergun-63c80b456d24','红外对射枪','2022-10-24 23:44:11','水洗布','金枪鱼生产线','56号位',56,'infraredcounter-63c80b456d24','体重','永康市瑞扬工贸有限公司','郝欣怡','技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (34,'infraredcountergun-e8cc96f17d99','红外对射枪','2022-10-25 00:00:24','PET标签','鱿鱼丝生产线','39号位',39,'infraredcounter-e8cc96f17d99','大物体','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','褚佳昊','人力资源部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (35,'infraredcountergun-70f01ad11659','红外对射枪','2022-10-25 00:00:27','不干胶标签','金龙鱼生产线','25号位',25,'infraredcounter-70f01ad11659','机械制造','介花潮公司','贺佳怡','安全监察部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (37,'infraredcountergun-3cffd01b13a5','红外对射枪','2022-10-25 00:00:32','吊牌','金枪鱼生产线','22号位',22,'infraredcounter-3cffd01b13a5','海鲜','深圳市贝约瀚有限公司','罗瑞堂','生产技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (39,'infraredcountergun-80c18538a01f','红外对射枪','2022-10-25 00:00:40','PET标签','马哈鱼生产线','18号位',18,'infraredcounter-80c18538a01f','海鲜','深圳市贝约瀚有限公司','余榕润','生产技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (40,'infraredcountergun-22fb2c6c98b6','红外对射枪','2022-10-25 00:02:59','吊牌','金枪鱼生产线','16号位',16,'infraredcounter-22fb2c6c98b6','海鲜','深圳市贝约瀚有限公司','雷佳毅','安全监察部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (41,'infraredcountergun-44dbb24d4409','红外对射枪','2022-10-25 00:03:05','PET标签','金枪鱼生产线','46号位',46,'infraredcounter-44dbb24d4409','水产','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','魏瑞辰','计划营销部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (42,'infraredcountergun-3faa596c012c','红外对射枪','2022-10-25 00:03:08','不干胶标签','鱿鱼丝生产线','27号位',27,'infraredcounter-3faa596c012c','水果批发','东莞市诚有成电子有限公司','周佳昊','计划营销部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (43,'infraredcountergun-2909b1ae64fc','红外对射枪','2022-10-25 00:03:10','POSTEK标签','马哈鱼生产线','54号位',54,'infraredcounter-2909b1ae64fc','海鲜','深圳市博途电子科技有限公司','顾嘉怡','财务部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (44,'infraredcountergun-78a97eb94832','红外对射枪','2022-10-25 00:03:39','PET标签','鱿鱼丝生产线','59号位',59,'infraredcounter-78a97eb94832','体重','深圳市晶衡科技有限公司是衡器、光学仪器等产品专业生产加工的公司','尹昊轩','生产技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (45,'infraredcountergun-660d6e316a6a','红外对射枪','2022-10-25 00:03:46','PET标签','金枪鱼生产线','30号位',30,'infraredcounter-660d6e316a6a','大物体','广州依芭衫工艺品商行','郝嘉怡','安全监察部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (46,'infraredcountergun-a09f1802598d','红外对射枪','2022-10-25 00:03:48','POSTEK标签','马哈鱼生产线','16号位',16,'infraredcounter-a09f1802598d','水产','深圳市博途电子科技有限公司','孔昊轩','生产技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (47,'infraredcountergun-0cab73c64002','红外对射枪','2022-10-25 00:04:10','不干胶标签','金枪鱼生产线','2号位',2,'infraredcounter-0cab73c64002','水果批发','东莞市诚有成电子有限公司','萧雄霖','人力资源部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (48,'infraredcountergun-cb25fabecd7b','红外对射枪','2022-10-25 00:05:14','吊牌','鱿鱼丝生产线','19号位',19,'infraredcounter-cb25fabecd7b','大物体','介花潮公司','陈清妍','计划营销部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (49,'infraredcountergun-ff7bc02e6dd5','红外对射枪','2022-10-25 00:05:17','吊牌','金枪鱼生产线','30号位',30,'infraredcounter-ff7bc02e6dd5','海鲜','明光市顺易达工艺品有限公司星狮称重设备(深圳)有限公司','罗浩晨','生产技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (50,'infraredcountergun-ed01603eed7e','红外对射枪','2022-10-25 00:05:21','POSTEK标签','鱿鱼丝生产线','2号位',2,'infraredcounter-ed01603eed7e','水产','永康市瑞扬工贸有限公司','郝夫子','计划营销部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (51,'infraredcountergun-736c5b4f2a80','红外对射枪','2022-10-25 00:05:35','POSTEK标签','马哈鱼生产线','13号位',13,'infraredcounter-736c5b4f2a80','体重','深圳市瑞鸿鑫贸易有限公司','奚欣源','生产技术部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (52,'infraredcountergun-8819e1e0fd8a','红外对射枪','2022-10-25 00:06:02','PET标签','马哈鱼生产线','12号位',12,'infraredcounter-8819e1e0fd8a','海鲜','深圳市瑞鸿鑫贸易有限公司','乐佳钰','财务部');
INSERT INTO `` (`id`,`BarCodeEquipment`,`DeviceType`,`PurchaseTime`,`ClassFacility`,`workStation`,`SubordinateStation`,`SensingDistance`,`GoNumber`,`SensingWay`,`manufacturer`,`PrincipalOfAssets`,`DepartmentOfOwnership`) VALUES (53,'electronicscale-8a4463319bb9','条码打印机','2022-10-25 00:24:51','0~21','马哈鱼生产线','21号位',8,'电子秤','深圳市瑞鸿鑫贸易有限公司','赛多利斯','水果批发','行政办公室');
